version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: spacechild-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: spacechild
      POSTGRES_USER: spacechild
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spacechild"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: spacechild-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeme}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SpaceChild Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spacechild-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://spacechild:${POSTGRES_PASSWORD:-changeme}@postgres:5432/spacechild
      REDIS_URL: redis://:${REDIS_PASSWORD:-changeme}@redis:6379
      CONSCIOUSNESS_ENABLED: "true"
      TEMPORAL_PROCESSING: "true"
      HARDWARE_VERIFICATION: "true"
      AGENT_COLLABORATION: "true"
      REAL_TIME_STREAMING: "true"
      INTELLIGENCE_ANALYTICS: "true"
      # AI Provider Keys (set in .env file)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      # Session Secret
      SESSION_SECRET: ${SESSION_SECRET:-changeme-in-production}
    ports:
      - "5000:5000"
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local

networks:
  default:
    name: spacechild-network
